import './globals.css'
import { Inter, Montserrat } from 'next/font/google'
import styles from './page.module.css'
import { Footer } from '@/components/shared/Footer/Footer'
import { Header } from '@/components/shared/Header/Header'

export const metadata = {
  title: 'Cat Wiki',
  description: 'Generated by Sergio',
}

const inter = Inter({ subsets: ['latin'] })

const montserrat = Montserrat({
  weight: '500', 
  subsets: ['latin'],
  style: 'normal'
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={montserrat.className}>
      <body className={inter.className}>
        <main className={styles.main}>  
          <Header/> 
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  )
}
