'use client'

import './globals.css'
import { Inter, Montserrat, Mystery_Quest } from 'next/font/google'
import styles from '../app/page.module.css'
import Image from 'next/image'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

const montserrat = Montserrat({
  weight: '500', 
  subsets: ['latin'],
  style: 'normal'
})

const mysteryQuest = Mystery_Quest({ 
  weight: '400', 
  subsets: ['latin'],
  style: 'normal'
});

const Footer = () => {
  return (
    <footer className="footer">
      <div>
        <Image style={{marginLeft: '80px'}} src={require("../images/LogoWhite.svg")} alt={''} height={42.67} width={127.72}/>
      </div>
      <p style={{marginRight: '32px'}}>&copy; created by Sergio - devChallenge.io 2021</p>
    </footer>
  );
};

export const metadata = {
  title: 'Cat Wiki',
  description: 'Generated by Sergio',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={montserrat.className}>
      <body className={inter.className}>
        <Link href={"../"} className={styles.title}>
          <Image src={require("../images/CatwikiLogo.svg")} alt={''} height={42.67} width={127.72}/>
        </Link>
        <main className={styles.main}>   
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  )
}
